[package]
org = "samith"
name = "pluginuser"
version = "0.1.0"
distribution = "2201.8.4"

[build-options]
observabilityIncluded = true

[[dependency]]
org = "samith"
name = "mediator"
version = "0.1.0"
repository="local"