[package]
org = "wso2"
name = "datamapper"
version = "0.1.0"
distribution = "2201.9.0-SNAPSHOT"

[build-options]
observabilityIncluded = true

[[platform.java17.dependency]]
path = "./ExternalFunction-1.0.0-SNAPSHOT.jar"
